### ISSUE TITLE
Edit Sound File Information

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#10]
As a **registered user**, I can **edit information for my sound file** so that I can **update the details of my audio content**.

## Acceptance Criteria- [ ] The user can update the title, description, and tags.
- [ ] The user can upload a new image.
- [ ] The user can update the location on a map.
- [ ] The user can submit the form.
- [ ] The user is redirected to the sound detail page.

## Tasks
