### ISSUE TITLE
Receive Notifications for New Likes, Comments, and Followers

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#18]
As a **registered user**, I can **receive notifications for new likes, comments, and followers** so that I can **stay engaged with my followers**.

## Acceptance Criteria- [ ] The user can see new notifications in the notification inbox.
- [ ] The user can see the number of new notifications in the navigation bar.
- [ ] The user can click on a notification to read it.
- [ ] The user can mark notifications as read.

## Tasks
