### ISSUE TITLE
USER STORY: Create Account

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#21]
As a **new user**, I can **create an account** so that I can **access the application**.

### Acceptance Criteria
- [ ] The user can enter a username, email address, and password.
- [ ] The user can submit the form.
- [ ] The user is redirected to the login page.

### Tasks
