### ISSUE TITLE
USER STORY: Add Information to Sound File

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#28]
As a **registered user**, I can **add information (title, description, image, tags) to my sound file** so that I can **provide details for my audio content**.

### Acceptance Criteria
- [ ] The user can enter a title, description, and tags.
- [ ] The user can upload an image.
- [ ] The user can submit the form.
- [ ] The user is redirected to the sound detail page.

### Tasks
