### ISSUE TITLE
USER STORY: Upload Sound File

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#36]
As a **registered user**, I can **upload a sound file** so that I can **share my sounds with other users**.

### Acceptance Criteria
- [ ] The user can upload a sound file.
- [ ] The user can submit the form.
- [ ] The user is redirected to the sound detail page.

### Tasks
