### ISSUE TITLE
USER STORY: Add Geolocation Data to Sound File

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#39]
As a **registered user**, I can **add geoloaction data to my sound file, either by choosing a location on a map or by allowing the browser to access my location** so that I can **provide location data for my  content**.

### Acceptance Criteria
- [ ] The user can choose a location on a map.
- [ ] The user can allow the browser to access their location.
- [ ] The user can submit the form.
- [ ] The user is redirected to the sound detail page.

### Tasks
