### ISSUE TITLE
USER STORY: Edit and Delete Comments

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#43]
As a **registered user**, I can **edit and delete my comments** so that I can **correct mistakes or withdraw comments**.

### Acceptance Criteria
- [ ] The user can edit their comments.
- [ ] The user can delete own comments.
- [ ] The user can see the updated comment on the sound detail page.
- [ ] The user can see that the comment was deleted on the sound detail page.

### Tasks
