### ISSUE TITLE
USER STORY: Follow/Unfollow Other Users

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#44]
As a **registered user**, I can **follow and unfollow other users** so that I can **stay updated on their uploaded content**.

### Acceptance Criteria
- [ ] The user can follow other users.
- [ ] The user can unfollow other users.
- [ ] The user can see the number of followers for each user.
- [ ] The number of followers is updated.

### Tasks
