### ISSUE TITLE
USER STORY: Receive Notifications for New Reports

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#47]
As a **staff user**, I can **receive notifications for new reports** so that I can **take appropriate action on flagged content**.

### Acceptance Criteria
- [ ] The user can see new notifications in the notification inbox.
- [ ] The user can see the number of new Reports in the navigation bar.
- [ ] The user can click on a notification to read it.
- [ ] The user can mark notifications as read.

### Tasks
