### ISSUE TITLE
USER STORY: Report Inappropriate Content

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#49]
As a **registered user**, I can **report sounds** so that I can **flag inappropriate content**.

### Acceptance Criteria
- [ ] The user can report sounds from the sound detail page.
- [ ] The user can select a reason for the report.
- [ ] The user can submit the form.
- [ ] The user can see a confirmation message.

### Tasks
