### ISSUE TITLE
USER STORY: See List of Sound Files

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#74]
As a **registered user**, I can **see a list of sound files** so that I can **explore other users sounds**.

### Acceptance Criteria
- [ ] The user can see a list of sound files.
- [ ] The user can see the sounds details (title, description, image, tags, location, likes, number of comments etc.).
- [ ] The user can play the sound file from the list.
- [ ] The user can click on a sound to access the sound detail page.

### Tasks
