### ISSUE TITLE
USER STORY: Sound Feed with Sounds from Followed Users

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#77]
As a **registered user**, I can **see a sounds feed with sounds from followed users** so that I can **discover content from users I follow**.

### Acceptance Criteria
- [ ] The user can see a list of sound files from followed users.
- [ ] The user can see the sounds details (title, description, image, tags, location, likes, number of comments etc.).
- [ ] The user can play the sound file from the list.
- [ ] The user can click on a sound to access the sound detail page.

### Tasks
