### ISSUE TITLE
USER STORY: See List of Liked Sounds

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#78]
As a **registered user**, I can **see a list of sound files I liked** so that I can **access my favourite sounds**.

### Acceptance Criteria
- [ ] The user can see a list of sound files they liked.
- [ ] The user can see the sounds details (title, description, image, tags, location, likes, number of comments etc.).
- [ ] The user can play the sound file from the list.
- [ ] The user can click on a sound to access the sound detail page.

### Tasks
