### ISSUE TITLE
USER STORY: Access Sound Detail Page

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#80]
As a **registered user**, I can **access a sound detail page with an audio player and the sounds details** so that I can **get more information on a specific sound**.

### Acceptance Criteria
- [ ] The user can access a sound detail page by clicking on a sound in the list of sounds or on a map marker.
- [ ] The user can see the sounds details (title, description, image, tags, location, likes, number of comments etc.).
- [ ] The user can play the sound file from the audio player.

### Tasks
