### ISSUE TITLE
USER STORY: Like and Unlike Sounds

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/se-test#82]
As a **registered user**, I can **like and unlike sounds** so that I can **express my appreciation for other users sounds**.

### Acceptance Criteria
- [ ] The user can like a sound.
- [ ] The user can unlike a sound.
- [ ] The user can see the number of likes for each sound.
- [ ] The number of likes is updated.

### Tasks
